baseURL = "https://example.org/"
languageCode = "en-us"
title = "CREATIVIDAD DIGITAL"
theme = "ananke"


[menu]
[[menu.main]]
identifier = 'about'
name = 'Acerca de...'
url = '/about/'

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'

